grammar: FHIRConnect/v1.0.0
type: model
metadata:
  name: CLUSTER.problem_qualifier.v2
  version: 0.0.1-alpha
spec:
  system: FHIR
  version: R4
  openEhrConfig:
    archetype: openEHR-EHR-CLUSTER.problem_qualifier.v2
    revision: 2.0.1
  fhirConfig:
    structureDefinition: http://hl7.org/fhir/StructureDefinition/BackboneElement

terminology:
  type: "local"
  conceptmap: "http://hl7.org/fhir/ConceptMap/eps-problem-qualifier-fhirconnect"

mappings:

  - name: "clinicalStatus"
    with:
      fhir: "$resource.clinicalStatus"
      openehr: "$archetype"
    followedBy:
      mappings:
        - name: "activeInactive"
          with:
            fhir: "coding"
            openehr: "items[at0003]"
          fhirCondition:
            targetRoot: "coding"
            targetAttribute: "code"
            operator: "one of"
            criterias:
              - "active"
              - "inactive"

        - name: "resolutionPhase"
          with:
            fhir: "coding"
            openehr: "items[at0083]"
          fhirCondition:
            targetRoot: "coding"
            targetAttribute: "code"
            operator: "one of"
            criterias:
              - "resolved"
              - "relapse"

        - name: "remissionStatus"
          with:
            fhir: "coding"
            openehr: "items[at0089]"
          fhirCondition:
            targetRoot: "coding"
            targetAttribute: "code"
            operator: "one of"
            criterias:
              - "remission"

        - name: "occurrencePhase"
          with:
            fhir: "coding"
            openehr: "items[at0071]"
          fhirCondition:
            targetRoot: "coding"
            targetAttribute: "code"
            operator: "one of"
            criterias:
              - "recurrence"
