grammar: FHIRConnect/v1.0.0
type: model
metadata:
  name: EVALUATION.problem_diagnosis.v1
  version: 0.0.1-alpha
spec:
  system: FHIR
  version: R4
  openEhrConfig:
    archetype: openEHR-EHR-EVALUATION.problem_diagnosis.v1
    revision: 1.4.1
  fhirConfig:
    structureDefinition: http://hl7.org/fhir/StructureDefinition/Condition

terminology:
  type: "local"
  conceptmap: "http://hl7.org/fhir/ConceptMap/eps-problem-diagnosis-fhirconnect"

preprocessor:
  fhirCondition:
    targetRoot: "$resource"
    targetAttribute: "verificationStatus.coding.code"
    operator: "not of"
    criteria: "entered-in-error"

mappings:

  - name: "problem"
    with:
      fhir: "$resource.code"
      openehr: "$archetype/data[at0001]/items[at0002]"

  - name: "bodySite"
    with:
      fhir: "$resource.bodySite"
      openehr: "$archetype/data[at0001]/items[at0012]"

  - name: "onsetDate"
    with:
      fhir: "$resource.onset.as(DateTime)"
      openehr: "$archetype/data[at0001]/items[at0077]"

  - name: "endDate"
    with:
      fhir: "$resource.abatement.as(DateTime)"
      openehr: "$archetype/data[at0001]/items[at0030]"

  - name: "severity"
    with:
      fhir: "$resource.severity.coding"
      openehr: "$archetype/data[at0001]/items[at0005]"

  - name: "diagnosisAssertionStatus"
    with:
      fhir: "$resource.verificationStatus.coding"
      openehr: "$archetype/data[at0001]/items[at0073]"

  - name: "stage"
    with:
      fhir: "$resource.stage"
      openehr: "$archetype/data[at0001]/items[openEHR-EHR-CLUSTER.clinical_evidence.v1, 'Stage']"
    slotArchetype: "CLUSTER.clinical_evidence.v1-stage"

  - name: "evidence"
    with:
      fhir: "$resource.evidence"
      openehr: "$archetype/data[at0001]/items[openEHR-EHR-CLUSTER.clinical_evidence.v1, 'Clinical evidence']"
    slotArchetype: "CLUSTER.clinical_evidence.v1-evidence"

  - name: "problemQualifier"
    with:
      fhir: "$resource"
      openehr: "$archetype/data[at0001]/items[openEHR-EHR-CLUSTER.problem_qualifier.v2]"
    slotArchetype: "CLUSTER.problem_qualifier.v2"

  - name: "note"
    with:
      fhir: "$resource.note.text"
      openehr: "$archetype/data[at0001]/items[at0069]"
